// <auto-generated />
using CustomerVehiclesCrudAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CustomerVehiclesCrudAPI.Migrations
{
    [DbContext(typeof(CustomerVehiclesContext))]
    partial class CustomerVehiclesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CustomerVehiclesCrudAPI.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("CustomerVehiclesCrudAPI.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerFk")
                        .HasColumnType("int")
                        .HasColumnName("CustomerFK");

                    b.Property<bool>("IsConnected")
                        .HasColumnType("bit");

                    b.Property<string>("RegNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("VIN");

                    b.HasKey("Id");

                    b.HasIndex("CustomerFk");

                    b.HasIndex(new[] { "Vin" }, "Vehicle_VIN")
                        .IsUnique();

                    b.ToTable("Vehicle");
                });

            modelBuilder.Entity("CustomerVehiclesCrudAPI.Models.Vehicle", b =>
                {
                    b.HasOne("CustomerVehiclesCrudAPI.Models.Customer", "CustomerFkNavigation")
                        .WithMany("Vehicles")
                        .HasForeignKey("CustomerFk")
                        .HasConstraintName("FK__Vehicle__Custome__2E1BDC42")
                        .IsRequired();

                    b.Navigation("CustomerFkNavigation");
                });

            modelBuilder.Entity("CustomerVehiclesCrudAPI.Models.Customer", b =>
                {
                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
